In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df1=pd.read_csv('test_FD001.txt', sep=' ',header=None)
df1

,0,1,2,3,4,5,6,7,8,9,...,18,19,20,21,22,23,24,25,26,27
0,1,1,0.0023,0.0003,100.0,518.67,643.02,1585.29,1398.21,14.62,...,8125.55,8.4052,0.03,392,2388,100.0,38.86,23.3735,NaN,NaN
1,1,2,-0.0027,-0.0003,100.0,518.67,641.71,1588.45,1395.42,14.62,...,8139.62,8.3803,0.03,393,2388,100.0,39.02,23.3916,NaN,NaN
2,1,3,0.0003,0.0001,100.0,518.67,642.46,1586.94,1401.34,14.62,...,8130.10,8.4441,0.03,393,2388,100.0,39.08,23.4166,NaN,NaN
3,1,4,0.0042,0.0000,100.0,518.67,642.44,1584.12,1406.42,14.62,...,8132.90,8.3917,0.03,391,2388,100.0,39.00,23.3737,NaN,NaN
4,1,5,0.0014,0.0000,100.0,518.67,642.51,1587.19,1401.92,14.62,...,8129.54,8.4031,0.03,390,2388,100.0,38.99,23.4130,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13091,100,194,0.0049,0.0000,100.0,518.67,643.24,1599.45,1415.79,14.62,...,8213.28,8.4715,0.03,394,2388,100.0,38.65,23.1974,NaN,NaN
13092,100,195,-0.0011,-0.0001,100.0,518.67,643.22,1595.69,1422.05,14.62,...,8210.85,8.4512,0.03,395,2388,100.0,38.57,23.2771,NaN,NaN
13093,100,196,-0.0006,-0.0003,100.0,518.67,643.44,1593.15,1406.82,14.62,...,8217.24,8.4569,0.03,395,2388,100.0,38.62,23.2051,NaN,NaN
13094,100,197,-0.0038,0.0001,100.0,518.67,643.26,1594.99,1419.36,14.62,...,8220.48,8.4711,0.03,395,2388,100.0,38.66,23.2699,NaN,NaN
13095,100,198,0.0013,0.0003,100.0,518.67,642.95,1601.62,1424.99,14.62,...,8214.64,8.4903,0.03,396,2388,100.0,38.70,23.1855,NaN,NaN

In [4]:
df1 = df1.drop([26, 27], axis='columns', errors='ignore')

df1

,0,1,2,3,4,5,6,7,8,9,...,16,17,18,19,20,21,22,23,24,25
0,1,1,0.0023,0.0003,100.0,518.67,643.02,1585.29,1398.21,14.62,...,521.72,2388.03,8125.55,8.4052,0.03,392,2388,100.0,38.86,23.3735
1,1,2,-0.0027,-0.0003,100.0,518.67,641.71,1588.45,1395.42,14.62,...,522.16,2388.06,8139.62,8.3803,0.03,393,2388,100.0,39.02,23.3916
2,1,3,0.0003,0.0001,100.0,518.67,642.46,1586.94,1401.34,14.62,...,521.97,2388.03,8130.10,8.4441,0.03,393,2388,100.0,39.08,23.4166
3,1,4,0.0042,0.0000,100.0,518.67,642.44,1584.12,1406.42,14.62,...,521.38,2388.05,8132.90,8.3917,0.03,391,2388,100.0,39.00,23.3737
4,1,5,0.0014,0.0000,100.0,518.67,642.51,1587.19,1401.92,14.62,...,522.15,2388.03,8129.54,8.4031,0.03,390,2388,100.0,38.99,23.4130
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13091,100,194,0.0049,0.0000,100.0,518.67,643.24,1599.45,1415.79,14.62,...,520.69,2388.00,8213.28,8.4715,0.03,394,2388,100.0,38.65,23.1974
13092,100,195,-0.0011,-0.0001,100.0,518.67,643.22,1595.69,1422.05,14.62,...,521.05,2388.09,8210.85,8.4512,0.03,395,2388,100.0,38.57,23.2771
13093,100,196,-0.0006,-0.0003,100.0,518.67,643.44,1593.15,1406.82,14.62,...,521.18,2388.04,8217.24,8.4569,0.03,395,2388,100.0,38.62,23.2051
13094,100,197,-0.0038,0.0001,100.0,518.67,643.26,1594.99,1419.36,14.62,...,521.33,2388.08,8220.48,8.4711,0.03,395,2388,100.0,38.66,23.2699
13095,100,198,0.0013,0.0003,100.0,518.67,642.95,1601.62,1424.99,14.62,...,521.07,2388.05,8214.64,8.4903,0.03,396,2388,100.0,38.70,23.1855

In [5]:
df1.columns=["ID","Cycle","OpSet1","OpSet2","OpSet3","SensorMeasure_1","SensorMeasure_2","SensorMeasure_3","SensorMeasure_4","SensorMeasure_5","SensorMeasure_6","SensorMeasure_7","SensorMeasure_8","SensorMeasure_9","SensorMeasure_10","SensorMeasure_11","SensorMeasure_12","SensorMeasure_13","SensorMeasure_14","SensorMeasure_15","SensorMeasure_16","SensorMeasure_17","SensorMeasure_18","SensorMeasure_19","SensorMeasure_20","SensorMeasure_21"]

In [6]:
given_no_of_cycles=[]
for i in range(1,len(df1['ID'].unique())+1):
    given_no_of_cycles.append(len(df1[df1['ID']==i]))
    print(len(df1[df1['ID']==i]))

given_no_of_cycles=np.array(given_no_of_cycles).reshape([cycle_ran_after.shape[0],1])

31
49
126
106
98
105
160
166
55
192
83
217
195
46
76
113
165
133
135
184
148
39
130
186
48
76
140
158
171
143
196
145
50
203
198
126
121
125
37
133
123
156
172
54
152
146
73
78
303
74
144
189
164
121
113
136
160
176
94
147
159
232
155
168
71
147
71
187
54
152
68
131
112
137
88
205
162
72
101
133
213
162
73
172
34
110
56
68
177
146
234
150
244
133
89
97
134
121
97
198

NameError: name 'cycle_ran_after' is not defined

We can see that data for 31cycles are available for engine1 in test set.Data for 40 cycles are available for engine2 and so on. Using the available data our goal is to predict RUL for each engine

In [7]:
len(df1['ID'].unique())

100

In [8]:
cycle_ran_after=pd.read_csv('RUL_FD001.txt', sep=' ',header=None)
cycle_ran_after = cycle_ran_after.drop([1],axis='columns')
cycle_ran_after=np.array(cycle_ran_after)
cycle_ran_after

array([[112],
       [ 98],
       [ 69],
       [ 82],
       [ 91],
       [ 93],
       [ 91],
       [ 95],
       [111],
       [ 96],
       [ 97],
       [124],
       [ 95],
       [107],
       [ 83],
       [ 84],
       [ 50],
       [ 28],
       [ 87],
       [ 16],
       [ 57],
       [111],
       [113],
       [ 20],
       [145],
       [119],
       [ 66],
       [ 97],
       [ 90],
       [115],
       [  8],
       [ 48],
       [106],
       [  7],
       [ 11],
       [ 19],
       [ 21],
       [ 50],
       [142],
       [ 28],
       [ 18],
       [ 10],
       [ 59],
       [109],
       [114],
       [ 47],
       [135],
       [ 92],
       [ 21],
       [ 79],
       [114],
       [ 29],
       [ 26],
       [ 97],
       [137],
       [ 15],
       [103],
       [ 37],
       [114],
       [100],
       [ 21],
       [ 54],
       [ 72],
       [ 28],
       [128],
       [ 14],
       [ 77],
       [  8],
       [121],
       [ 94],
       [118],
       [ 50],
       [131],
       [126],
       [113],
       [ 10],
       [ 34],
       [107],
       [ 63],
       [ 90],
       [  8],
       [  9],
       [137],
       [ 58],
       [118],
       [ 89],
       [116],
       [115],
       [136],
       [ 28],
       [ 38],
       [ 20],
       [ 85],
       [ 55],
       [128],
       [137],
       [ 82],
       [ 59],
       [117],
       [ 20]], dtype=int64)

In [9]:
EOL = []
for i in df1['ID']:  # Use unique IDs to avoid redundant iterations
     EOL.append(given_no_of_cycles[i-1]+cycle_ran_after[i-1])
EOL=np.array(EOL).reshape([len(EOL),1])

In [10]:
EOL.shape

(13096, 1)

In [11]:
df1['EOL']=EOL
df1

,ID,Cycle,OpSet1,OpSet2,OpSet3,SensorMeasure_1,SensorMeasure_2,SensorMeasure_3,SensorMeasure_4,SensorMeasure_5,...,SensorMeasure_13,SensorMeasure_14,SensorMeasure_15,SensorMeasure_16,SensorMeasure_17,SensorMeasure_18,SensorMeasure_19,SensorMeasure_20,SensorMeasure_21,EOL
0,1,1,0.0023,0.0003,100.0,518.67,643.02,1585.29,1398.21,14.62,...,2388.03,8125.55,8.4052,0.03,392,2388,100.0,38.86,23.3735,143
1,1,2,-0.0027,-0.0003,100.0,518.67,641.71,1588.45,1395.42,14.62,...,2388.06,8139.62,8.3803,0.03,393,2388,100.0,39.02,23.3916,143
2,1,3,0.0003,0.0001,100.0,518.67,642.46,1586.94,1401.34,14.62,...,2388.03,8130.10,8.4441,0.03,393,2388,100.0,39.08,23.4166,143
3,1,4,0.0042,0.0000,100.0,518.67,642.44,1584.12,1406.42,14.62,...,2388.05,8132.90,8.3917,0.03,391,2388,100.0,39.00,23.3737,143
4,1,5,0.0014,0.0000,100.0,518.67,642.51,1587.19,1401.92,14.62,...,2388.03,8129.54,8.4031,0.03,390,2388,100.0,38.99,23.4130,143
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13091,100,194,0.0049,0.0000,100.0,518.67,643.24,1599.45,1415.79,14.62,...,2388.00,8213.28,8.4715,0.03,394,2388,100.0,38.65,23.1974,218
13092,100,195,-0.0011,-0.0001,100.0,518.67,643.22,1595.69,1422.05,14.62,...,2388.09,8210.85,8.4512,0.03,395,2388,100.0,38.57,23.2771,218
13093,100,196,-0.0006,-0.0003,100.0,518.67,643.44,1593.15,1406.82,14.62,...,2388.04,8217.24,8.4569,0.03,395,2388,100.0,38.62,23.2051,218
13094,100,197,-0.0038,0.0001,100.0,518.67,643.26,1594.99,1419.36,14.62,...,2388.08,8220.48,8.4711,0.03,395,2388,100.0,38.66,23.2699,218
13095,100,198,0.0013,0.0003,100.0,518.67,642.95,1601.62,1424.99,14.62,...,2388.05,8214.64,8.4903,0.03,396,2388,100.0,38.70,23.1855,218

In [12]:
df1['LR']=df1['Cycle']/df1['EOL']
#Drop ID and EOL

df1=df1.drop(columns=['ID','EOL'])
df1

,Cycle,OpSet1,OpSet2,OpSet3,SensorMeasure_1,SensorMeasure_2,SensorMeasure_3,SensorMeasure_4,SensorMeasure_5,SensorMeasure_6,...,SensorMeasure_13,SensorMeasure_14,SensorMeasure_15,SensorMeasure_16,SensorMeasure_17,SensorMeasure_18,SensorMeasure_19,SensorMeasure_20,SensorMeasure_21,LR
0,1,0.0023,0.0003,100.0,518.67,643.02,1585.29,1398.21,14.62,21.61,...,2388.03,8125.55,8.4052,0.03,392,2388,100.0,38.86,23.3735,0.006993
1,2,-0.0027,-0.0003,100.0,518.67,641.71,1588.45,1395.42,14.62,21.61,...,2388.06,8139.62,8.3803,0.03,393,2388,100.0,39.02,23.3916,0.013986
2,3,0.0003,0.0001,100.0,518.67,642.46,1586.94,1401.34,14.62,21.61,...,2388.03,8130.10,8.4441,0.03,393,2388,100.0,39.08,23.4166,0.020979
3,4,0.0042,0.0000,100.0,518.67,642.44,1584.12,1406.42,14.62,21.61,...,2388.05,8132.90,8.3917,0.03,391,2388,100.0,39.00,23.3737,0.027972
4,5,0.0014,0.0000,100.0,518.67,642.51,1587.19,1401.92,14.62,21.61,...,2388.03,8129.54,8.4031,0.03,390,2388,100.0,38.99,23.4130,0.034965
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13091,194,0.0049,0.0000,100.0,518.67,643.24,1599.45,1415.79,14.62,21.61,...,2388.00,8213.28,8.4715,0.03,394,2388,100.0,38.65,23.1974,0.889908
13092,195,-0.0011,-0.0001,100.0,518.67,643.22,1595.69,1422.05,14.62,21.61,...,2388.09,8210.85,8.4512,0.03,395,2388,100.0,38.57,23.2771,0.894495
13093,196,-0.0006,-0.0003,100.0,518.67,643.44,1593.15,1406.82,14.62,21.61,...,2388.04,8217.24,8.4569,0.03,395,2388,100.0,38.62,23.2051,0.899083
13094,197,-0.0038,0.0001,100.0,518.67,643.26,1594.99,1419.36,14.62,21.61,...,2388.08,8220.48,8.4711,0.03,395,2388,100.0,38.66,23.2699,0.903670
13095,198,0.0013,0.0003,100.0,518.67,642.95,1601.62,1424.99,14.62,21.61,...,2388.05,8214.64,8.4903,0.03,396,2388,100.0,38.70,23.1855,0.908257

In [13]:
labels=[]
for i in range(0,len(df1)):
    if np.array(df1['LR'])[i]<=0.6:
        labels.append(0)
    elif np.array(df1['LR'])[i]<=0.8:
        labels.append(1)
    else:
        labels.append(2)

df1['labels']=labels
df1=df1.drop(columns=['LR'])
df1

,Cycle,OpSet1,OpSet2,OpSet3,SensorMeasure_1,SensorMeasure_2,SensorMeasure_3,SensorMeasure_4,SensorMeasure_5,SensorMeasure_6,...,SensorMeasure_13,SensorMeasure_14,SensorMeasure_15,SensorMeasure_16,SensorMeasure_17,SensorMeasure_18,SensorMeasure_19,SensorMeasure_20,SensorMeasure_21,labels
0,1,0.0023,0.0003,100.0,518.67,643.02,1585.29,1398.21,14.62,21.61,...,2388.03,8125.55,8.4052,0.03,392,2388,100.0,38.86,23.3735,0
1,2,-0.0027,-0.0003,100.0,518.67,641.71,1588.45,1395.42,14.62,21.61,...,2388.06,8139.62,8.3803,0.03,393,2388,100.0,39.02,23.3916,0
2,3,0.0003,0.0001,100.0,518.67,642.46,1586.94,1401.34,14.62,21.61,...,2388.03,8130.10,8.4441,0.03,393,2388,100.0,39.08,23.4166,0
3,4,0.0042,0.0000,100.0,518.67,642.44,1584.12,1406.42,14.62,21.61,...,2388.05,8132.90,8.3917,0.03,391,2388,100.0,39.00,23.3737,0
4,5,0.0014,0.0000,100.0,518.67,642.51,1587.19,1401.92,14.62,21.61,...,2388.03,8129.54,8.4031,0.03,390,2388,100.0,38.99,23.4130,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13091,194,0.0049,0.0000,100.0,518.67,643.24,1599.45,1415.79,14.62,21.61,...,2388.00,8213.28,8.4715,0.03,394,2388,100.0,38.65,23.1974,2
13092,195,-0.0011,-0.0001,100.0,518.67,643.22,1595.69,1422.05,14.62,21.61,...,2388.09,8210.85,8.4512,0.03,395,2388,100.0,38.57,23.2771,2
13093,196,-0.0006,-0.0003,100.0,518.67,643.44,1593.15,1406.82,14.62,21.61,...,2388.04,8217.24,8.4569,0.03,395,2388,100.0,38.62,23.2051,2
13094,197,-0.0038,0.0001,100.0,518.67,643.26,1594.99,1419.36,14.62,21.61,...,2388.08,8220.48,8.4711,0.03,395,2388,100.0,38.66,23.2699,2
13095,198,0.0013,0.0003,100.0,518.67,642.95,1601.62,1424.99,14.62,21.61,...,2388.05,8214.64,8.4903,0.03,396,2388,100.0,38.70,23.1855,2

In [14]:
df1.to_csv('text_classification_4.csv', index=None)

,Cycle,OpSet1,OpSet2,OpSet3,SensorMeasure_1,SensorMeasure_2,SensorMeasure_3,SensorMeasure_4,SensorMeasure_5,SensorMeasure_6,...,SensorMeasure_13,SensorMeasure_14,SensorMeasure_15,SensorMeasure_16,SensorMeasure_17,SensorMeasure_18,SensorMeasure_19,SensorMeasure_20,SensorMeasure_21,labels
0,1,0.0023,0.0003,100.0,518.67,643.02,1585.29,1398.21,14.62,21.61,...,2388.03,8125.55,8.4052,0.03,392,2388,100.0,38.86,23.3735,0
1,2,-0.0027,-0.0003,100.0,518.67,641.71,1588.45,1395.42,14.62,21.61,...,2388.06,8139.62,8.3803,0.03,393,2388,100.0,39.02,23.3916,0
2,3,0.0003,0.0001,100.0,518.67,642.46,1586.94,1401.34,14.62,21.61,...,2388.03,8130.10,8.4441,0.03,393,2388,100.0,39.08,23.4166,0
3,4,0.0042,0.0000,100.0,518.67,642.44,1584.12,1406.42,14.62,21.61,...,2388.05,8132.90,8.3917,0.03,391,2388,100.0,39.00,23.3737,0
4,5,0.0014,0.0000,100.0,518.67,642.51,1587.19,1401.92,14.62,21.61,...,2388.03,8129.54,8.4031,0.03,390,2388,100.0,38.99,23.4130,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13091,194,0.0049,0.0000,100.0,518.67,643.24,1599.45,1415.79,14.62,21.61,...,2388.00,8213.28,8.4715,0.03,394,2388,100.0,38.65,23.1974,2
13092,195,-0.0011,-0.0001,100.0,518.67,643.22,1595.69,1422.05,14.62,21.61,...,2388.09,8210.85,8.4512,0.03,395,2388,100.0,38.57,23.2771,2
13093,196,-0.0006,-0.0003,100.0,518.67,643.44,1593.15,1406.82,14.62,21.61,...,2388.04,8217.24,8.4569,0.03,395,2388,100.0,38.62,23.2051,2
13094,197,-0.0038,0.0001,100.0,518.67,643.26,1594.99,1419.36,14.62,21.61,...,2388.08,8220.48,8.4711,0.03,395,2388,100.0,38.66,23.2699,2
13095,198,0.0013,0.0003,100.0,518.67,642.95,1601.62,1424.99,14.62,21.61,...,2388.05,8214.64,8.4903,0.03,396,2388,100.0,38.70,23.1855,2

In [15]:
df2=pd.read_csv('test_FD002.txt', sep=' ',header=None)
df2

,0,1,2,3,4,5,6,7,8,9,...,18,19,20,21,22,23,24,25,26,27
0,1,1,9.9987,0.2502,100.0,489.05,605.03,1497.17,1304.99,10.52,...,8114.10,8.6476,0.03,369,2319,100.00,28.42,17.1551,NaN,NaN
1,1,2,20.0026,0.7000,100.0,491.19,607.82,1481.20,1246.11,9.35,...,8053.06,9.2405,0.02,364,2324,100.00,24.29,14.8039,NaN,NaN
2,1,3,35.0045,0.8400,100.0,449.44,556.00,1359.08,1128.36,5.48,...,8053.04,9.3472,0.02,333,2223,100.00,14.98,8.9125,NaN,NaN
3,1,4,42.0066,0.8410,100.0,445.00,550.17,1349.69,1127.89,3.91,...,8066.90,9.3961,0.02,332,2212,100.00,10.35,6.4181,NaN,NaN
4,1,5,24.9985,0.6213,60.0,462.54,536.72,1253.18,1050.69,7.05,...,7865.66,10.8682,0.02,305,1915,84.93,14.31,8.5740,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33986,259,119,35.0015,0.8403,100.0,449.44,555.56,1366.01,1129.47,5.48,...,8088.36,9.3215,0.02,334,2223,100.00,14.94,8.9065,NaN,NaN
33987,259,120,42.0066,0.8405,100.0,445.00,549.42,1351.13,1123.86,3.91,...,8108.48,9.3542,0.02,332,2212,100.00,10.57,6.4075,NaN,NaN
33988,259,121,42.0061,0.8400,100.0,445.00,549.65,1349.14,1118.91,3.91,...,8098.77,9.3836,0.02,331,2212,100.00,10.57,6.4805,NaN,NaN
33989,259,122,0.0024,0.0003,100.0,518.67,642.58,1589.61,1408.16,14.62,...,8161.85,8.4279,0.03,393,2388,100.00,39.08,23.3589,NaN,NaN
33990,259,123,42.0033,0.8400,100.0,445.00,549.77,1342.50,1126.96,3.91,...,8105.28,9.3458,0.02,331,2212,100.00,10.63,6.3480,NaN,NaN

In [16]:
df2 = df2.drop([26, 27], axis='columns', errors='ignore')

df2

,0,1,2,3,4,5,6,7,8,9,...,16,17,18,19,20,21,22,23,24,25
0,1,1,9.9987,0.2502,100.0,489.05,605.03,1497.17,1304.99,10.52,...,371.69,2388.18,8114.10,8.6476,0.03,369,2319,100.00,28.42,17.1551
1,1,2,20.0026,0.7000,100.0,491.19,607.82,1481.20,1246.11,9.35,...,315.32,2388.12,8053.06,9.2405,0.02,364,2324,100.00,24.29,14.8039
2,1,3,35.0045,0.8400,100.0,449.44,556.00,1359.08,1128.36,5.48,...,183.04,2387.75,8053.04,9.3472,0.02,333,2223,100.00,14.98,8.9125
3,1,4,42.0066,0.8410,100.0,445.00,550.17,1349.69,1127.89,3.91,...,130.40,2387.72,8066.90,9.3961,0.02,332,2212,100.00,10.35,6.4181
4,1,5,24.9985,0.6213,60.0,462.54,536.72,1253.18,1050.69,7.05,...,164.56,2028.05,7865.66,10.8682,0.02,305,1915,84.93,14.31,8.5740
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33986,259,119,35.0015,0.8403,100.0,449.44,555.56,1366.01,1129.47,5.48,...,183.05,2388.39,8088.36,9.3215,0.02,334,2223,100.00,14.94,8.9065
33987,259,120,42.0066,0.8405,100.0,445.00,549.42,1351.13,1123.86,3.91,...,130.74,2388.31,8108.48,9.3542,0.02,332,2212,100.00,10.57,6.4075
33988,259,121,42.0061,0.8400,100.0,445.00,549.65,1349.14,1118.91,3.91,...,130.96,2388.34,8098.77,9.3836,0.02,331,2212,100.00,10.57,6.4805
33989,259,122,0.0024,0.0003,100.0,518.67,642.58,1589.61,1408.16,14.62,...,522.25,2388.00,8161.85,8.4279,0.03,393,2388,100.00,39.08,23.3589
33990,259,123,42.0033,0.8400,100.0,445.00,549.77,1342.50,1126.96,3.91,...,130.93,2388.40,8105.28,9.3458,0.02,331,2212,100.00,10.63,6.3480

In [17]:
df2.columns=["ID","Cycle","OpSet1","OpSet2","OpSet3","SensorMeasure_1","SensorMeasure_2","SensorMeasure_3","SensorMeasure_4","SensorMeasure_5","SensorMeasure_6","SensorMeasure_7","SensorMeasure_8","SensorMeasure_9","SensorMeasure_10","SensorMeasure_11","SensorMeasure_12","SensorMeasure_13","SensorMeasure_14","SensorMeasure_15","SensorMeasure_16","SensorMeasure_17","SensorMeasure_18","SensorMeasure_19","SensorMeasure_20","SensorMeasure_21"]

In [18]:
given_no_of_cycles=[]
for i in range(1,len(df2['ID'].unique())+1):
    given_no_of_cycles.append(len(df2[df2['ID']==i]))
    print(len(df2[df2['ID']==i]))

given_no_of_cycles=np.array(given_no_of_cycles).reshape([cycle_ran_after.shape[0],1])

258
55
165
86
148
63
184
173
161
84
162
74
164
160
165
88
264
40
172
101
128
159
49
210
147
76
68
23
101
184
123
170
135
52
77
163
49
127
149
183
210
137
184
164
195
132
81
132
65
164
37
165
149
74
123
73
76
247
22
144
70
205
174
233
367
63
146
218
158
264
65
143
151
103
192
222
67
128
113
278
76
96
21
204
183
83
131
166
59
163
278
123
76
117
78
140
213
113
163
149
38
122
186
141
61
72
132
174
144
219
131
109
45
153
210
171
55
97
202
160
59
29
61
149
79
99
126
110
218
141
73
122
186
186
120
77
226
200
116
306
69
163
226
143
142
144
78
157
70
196
141
90
146
58
72
75
161
171
187
124
174
185
144
199
35
97
78
107
80
85
243
128
117
51
83
200
191
54
156
154
199
134
150
64
254
166
84
86
178
158
95
161
245
50
262
109
59
120
117
60
25
124
115
41
31
162
141
166
131
182
155
187
159
75
71
100
49
33
161
54
55
180
29
43
166
165
180
44
109
125
187
159
40
147
102
274
235
94
106
50
44
194
40
49
265
80
87
162
36
234
64
249
139
131
150
59
199
98
123

ValueError: cannot reshape array of size 259 into shape (100,1)

In [19]:
len(df2['ID'].unique())

259

In [20]:
cycle_ran_after=pd.read_csv('RUL_FD002.txt', sep=' ',header=None)
cycle_ran_after = cycle_ran_after.drop([1],axis='columns')
cycle_ran_after=np.array(cycle_ran_after)
cycle_ran_after

array([[ 18],
       [ 79],
       [106],
       [110],
       [ 15],
       [155],
       [  6],
       [ 90],
       [ 11],
       [ 79],
       [  6],
       [ 73],
       [ 30],
       [ 11],
       [ 37],
       [ 67],
       [ 68],
       [ 99],
       [ 22],
       [ 54],
       [ 97],
       [ 10],
       [142],
       [ 77],
       [ 88],
       [163],
       [126],
       [138],
       [ 83],
       [ 78],
       [ 75],
       [ 11],
       [ 53],
       [173],
       [ 63],
       [100],
       [151],
       [ 55],
       [ 48],
       [ 37],
       [ 44],
       [ 27],
       [ 18],
       [  6],
       [ 15],
       [112],
       [131],
       [ 13],
       [122],
       [ 13],
       [ 98],
       [ 53],
       [ 52],
       [106],
       [103],
       [152],
       [123],
       [ 26],
       [178],
       [ 73],
       [169],
       [ 39],
       [ 39],
       [ 14],
       [ 11],
       [121],
       [ 86],
       [ 56],
       [115],
       [ 17],
       [148],
       [104],
       [ 78],
       [ 86],
       [ 98],
       [ 36],
       [ 94],
       [ 52],
       [ 91],
       [ 15],
       [141],
       [ 74],
       [146],
       [ 17],
       [ 47],
       [194],
       [ 21],
       [ 79],
       [ 97],
       [  8],
       [  9],
       [ 73],
       [183],
       [ 97],
       [ 73],
       [ 49],
       [ 31],
       [ 97],
       [  9],
       [ 14],
       [106],
       [  8],
       [  8],
       [106],
       [116],
       [120],
       [ 61],
       [168],
       [ 35],
       [ 80],
       [  9],
       [ 50],
       [151],
       [ 78],
       [ 91],
       [  7],
       [181],
       [150],
       [106],
       [ 15],
       [ 67],
       [145],
       [180],
       [  7],
       [179],
       [124],
       [ 82],
       [108],
       [ 79],
       [121],
       [120],
       [ 39],
       [ 38],
       [  9],
       [167],
       [ 87],
       [ 88],
       [  7],
       [ 51],
       [ 55],
       [155],
       [ 47],
       [ 81],
       [ 43],
       [ 98],
       [ 10],
       [ 92],
       [ 11],
       [165],
       [ 34],
       [115],
       [ 59],
       [ 99],
       [103],
       [108],
       [ 83],
       [171],
       [ 15],
       [  9],
       [ 42],
       [ 13],
       [ 41],
       [ 88],
       [ 14],
       [155],
       [188],
       [ 96],
       [ 82],
       [135],
       [182],
       [ 36],
       [107],
       [ 14],
       [ 95],
       [142],
       [ 23],
       [  6],
       [144],
       [ 35],
       [ 97],
       [ 68],
       [ 14],
       [ 67],
       [191],
       [ 19],
       [ 10],
       [158],
       [183],
       [ 43],
       [ 12],
       [148],
       [ 13],
       [ 37],
       [122],
       [ 80],
       [ 93],
       [132],
       [ 32],
       [103],
       [174],
       [111],
       [ 68],
       [192],
       [121],
       [134],
       [ 48],
       [ 85],
       [  8],
       [ 23],
       [  8],
       [  6],
       [ 57],
       [ 83],
       [172],
       [101],
       [ 81],
       [ 86],
       [165],
       [ 73],
       [121],
       [139],
       [ 75],
       [151],
       [145],
       [ 11],
       [108],
       [ 14],
       [126],
       [ 61],
       [ 85],
       [  8],
       [101],
       [153],
       [ 89],
       [190],
       [ 12],
       [ 62],
       [134],
       [101],
       [121],
       [167],
       [ 17],
       [161],
       [181],
       [ 16],
       [152],
       [148],
       [ 56],
       [111],
       [ 23],
       [ 84],
       [ 12],
       [ 43],
       [ 48],
       [122],
       [191],
       [ 56],
       [131],
       [ 51]], dtype=int64)

In [21]:
EOL = []
for i in df2['ID']:  # Use unique IDs to avoid redundant iterations
     EOL.append(given_no_of_cycles[i-1]+cycle_ran_after[i-1])
EOL=np.array(EOL).reshape([len(EOL),1])

In [22]:
EOL.shape

(33991, 1)

In [23]:
df2['EOL']=EOL
df2

,ID,Cycle,OpSet1,OpSet2,OpSet3,SensorMeasure_1,SensorMeasure_2,SensorMeasure_3,SensorMeasure_4,SensorMeasure_5,...,SensorMeasure_13,SensorMeasure_14,SensorMeasure_15,SensorMeasure_16,SensorMeasure_17,SensorMeasure_18,SensorMeasure_19,SensorMeasure_20,SensorMeasure_21,EOL
0,1,1,9.9987,0.2502,100.0,489.05,605.03,1497.17,1304.99,10.52,...,2388.18,8114.10,8.6476,0.03,369,2319,100.00,28.42,17.1551,276
1,1,2,20.0026,0.7000,100.0,491.19,607.82,1481.20,1246.11,9.35,...,2388.12,8053.06,9.2405,0.02,364,2324,100.00,24.29,14.8039,276
2,1,3,35.0045,0.8400,100.0,449.44,556.00,1359.08,1128.36,5.48,...,2387.75,8053.04,9.3472,0.02,333,2223,100.00,14.98,8.9125,276
3,1,4,42.0066,0.8410,100.0,445.00,550.17,1349.69,1127.89,3.91,...,2387.72,8066.90,9.3961,0.02,332,2212,100.00,10.35,6.4181,276
4,1,5,24.9985,0.6213,60.0,462.54,536.72,1253.18,1050.69,7.05,...,2028.05,7865.66,10.8682,0.02,305,1915,84.93,14.31,8.5740,276
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33986,259,119,35.0015,0.8403,100.0,449.44,555.56,1366.01,1129.47,5.48,...,2388.39,8088.36,9.3215,0.02,334,2223,100.00,14.94,8.9065,174
33987,259,120,42.0066,0.8405,100.0,445.00,549.42,1351.13,1123.86,3.91,...,2388.31,8108.48,9.3542,0.02,332,2212,100.00,10.57,6.4075,174
33988,259,121,42.0061,0.8400,100.0,445.00,549.65,1349.14,1118.91,3.91,...,2388.34,8098.77,9.3836,0.02,331,2212,100.00,10.57,6.4805,174
33989,259,122,0.0024,0.0003,100.0,518.67,642.58,1589.61,1408.16,14.62,...,2388.00,8161.85,8.4279,0.03,393,2388,100.00,39.08,23.3589,174
33990,259,123,42.0033,0.8400,100.0,445.00,549.77,1342.50,1126.96,3.91,...,2388.40,8105.28,9.3458,0.02,331,2212,100.00,10.63,6.3480,174

In [24]:
df2['LR']=df2['Cycle']/df2['EOL']
#Drop ID and EOL

df2=df2.drop(columns=['ID','EOL'])
df2

,Cycle,OpSet1,OpSet2,OpSet3,SensorMeasure_1,SensorMeasure_2,SensorMeasure_3,SensorMeasure_4,SensorMeasure_5,SensorMeasure_6,...,SensorMeasure_13,SensorMeasure_14,SensorMeasure_15,SensorMeasure_16,SensorMeasure_17,SensorMeasure_18,SensorMeasure_19,SensorMeasure_20,SensorMeasure_21,LR
0,1,9.9987,0.2502,100.0,489.05,605.03,1497.17,1304.99,10.52,15.49,...,2388.18,8114.10,8.6476,0.03,369,2319,100.00,28.42,17.1551,0.003623
1,2,20.0026,0.7000,100.0,491.19,607.82,1481.20,1246.11,9.35,13.66,...,2388.12,8053.06,9.2405,0.02,364,2324,100.00,24.29,14.8039,0.007246
2,3,35.0045,0.8400,100.0,449.44,556.00,1359.08,1128.36,5.48,8.00,...,2387.75,8053.04,9.3472,0.02,333,2223,100.00,14.98,8.9125,0.010870
3,4,42.0066,0.8410,100.0,445.00,550.17,1349.69,1127.89,3.91,5.71,...,2387.72,8066.90,9.3961,0.02,332,2212,100.00,10.35,6.4181,0.014493
4,5,24.9985,0.6213,60.0,462.54,536.72,1253.18,1050.69,7.05,9.03,...,2028.05,7865.66,10.8682,0.02,305,1915,84.93,14.31,8.5740,0.018116
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33986,119,35.0015,0.8403,100.0,449.44,555.56,1366.01,1129.47,5.48,8.00,...,2388.39,8088.36,9.3215,0.02,334,2223,100.00,14.94,8.9065,0.683908
33987,120,42.0066,0.8405,100.0,445.00,549.42,1351.13,1123.86,3.91,5.72,...,2388.31,8108.48,9.3542,0.02,332,2212,100.00,10.57,6.4075,0.689655
33988,121,42.0061,0.8400,100.0,445.00,549.65,1349.14,1118.91,3.91,5.72,...,2388.34,8098.77,9.3836,0.02,331,2212,100.00,10.57,6.4805,0.695402
33989,122,0.0024,0.0003,100.0,518.67,642.58,1589.61,1408.16,14.62,21.61,...,2388.00,8161.85,8.4279,0.03,393,2388,100.00,39.08,23.3589,0.701149
33990,123,42.0033,0.8400,100.0,445.00,549.77,1342.50,1126.96,3.91,5.71,...,2388.40,8105.28,9.3458,0.02,331,2212,100.00,10.63,6.3480,0.706897

In [25]:
df2.to_csv('text_classification_5.csv', index=None)

In [26]:
df3=pd.read_csv('test_FD003.txt', sep=' ',header=None)
df3

,0,1,2,3,4,5,6,7,8,9,...,18,19,20,21,22,23,24,25,26,27
0,1,1,-0.0017,-0.0004,100.0,518.67,641.94,1581.93,1396.93,14.62,...,8133.48,8.3760,0.03,391,2388,100.0,39.07,23.4468,NaN,NaN
1,1,2,0.0006,-0.0002,100.0,518.67,642.02,1584.86,1398.90,14.62,...,8137.44,8.4062,0.03,391,2388,100.0,39.04,23.4807,NaN,NaN
2,1,3,0.0014,-0.0003,100.0,518.67,641.68,1581.78,1391.92,14.62,...,8138.25,8.3553,0.03,391,2388,100.0,39.10,23.4244,NaN,NaN
3,1,4,0.0027,0.0001,100.0,518.67,642.20,1584.53,1395.34,14.62,...,8137.07,8.3709,0.03,392,2388,100.0,38.97,23.4782,NaN,NaN
4,1,5,-0.0001,0.0001,100.0,518.67,642.46,1589.03,1395.86,14.62,...,8134.20,8.4146,0.03,391,2388,100.0,39.09,23.3950,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16591,100,243,0.0011,-0.0003,100.0,518.67,643.04,1594.99,1411.28,14.62,...,8162.24,8.2939,0.03,395,2388,100.0,39.40,23.4949,NaN,NaN
16592,100,244,-0.0024,0.0002,100.0,518.67,642.47,1591.27,1417.64,14.62,...,8163.24,8.3247,0.03,394,2388,100.0,39.42,23.6011,NaN,NaN
16593,100,245,-0.0053,0.0002,100.0,518.67,642.70,1593.81,1412.70,14.62,...,8162.12,8.3264,0.03,394,2388,100.0,39.43,23.5482,NaN,NaN
16594,100,246,-0.0006,0.0001,100.0,518.67,642.19,1595.63,1406.58,14.62,...,8164.20,8.2908,0.03,395,2388,100.0,39.40,23.6687,NaN,NaN
16595,100,247,0.0023,0.0004,100.0,518.67,643.19,1592.54,1407.20,14.62,...,8169.24,8.3191,0.03,392,2388,100.0,39.41,23.6536,NaN,NaN

In [27]:
df3 = df3.drop([26, 27], axis='columns', errors='ignore')

df3

,0,1,2,3,4,5,6,7,8,9,...,16,17,18,19,20,21,22,23,24,25
0,1,1,-0.0017,-0.0004,100.0,518.67,641.94,1581.93,1396.93,14.62,...,521.89,2387.94,8133.48,8.3760,0.03,391,2388,100.0,39.07,23.4468
1,1,2,0.0006,-0.0002,100.0,518.67,642.02,1584.86,1398.90,14.62,...,521.85,2388.01,8137.44,8.4062,0.03,391,2388,100.0,39.04,23.4807
2,1,3,0.0014,-0.0003,100.0,518.67,641.68,1581.78,1391.92,14.62,...,522.10,2387.94,8138.25,8.3553,0.03,391,2388,100.0,39.10,23.4244
3,1,4,0.0027,0.0001,100.0,518.67,642.20,1584.53,1395.34,14.62,...,522.45,2387.96,8137.07,8.3709,0.03,392,2388,100.0,38.97,23.4782
4,1,5,-0.0001,0.0001,100.0,518.67,642.46,1589.03,1395.86,14.62,...,521.91,2387.97,8134.20,8.4146,0.03,391,2388,100.0,39.09,23.3950
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16591,100,243,0.0011,-0.0003,100.0,518.67,643.04,1594.99,1411.28,14.62,...,529.23,2388.24,8162.24,8.2939,0.03,395,2388,100.0,39.40,23.4949
16592,100,244,-0.0024,0.0002,100.0,518.67,642.47,1591.27,1417.64,14.62,...,529.27,2388.26,8163.24,8.3247,0.03,394,2388,100.0,39.42,23.6011
16593,100,245,-0.0053,0.0002,100.0,518.67,642.70,1593.81,1412.70,14.62,...,529.48,2388.28,8162.12,8.3264,0.03,394,2388,100.0,39.43,23.5482
16594,100,246,-0.0006,0.0001,100.0,518.67,642.19,1595.63,1406.58,14.62,...,529.39,2388.33,8164.20,8.2908,0.03,395,2388,100.0,39.40,23.6687
16595,100,247,0.0023,0.0004,100.0,518.67,643.19,1592.54,1407.20,14.62,...,529.59,2388.29,8169.24,8.3191,0.03,392,2388,100.0,39.41,23.6536

In [28]:
df3.columns=["ID","Cycle","OpSet1","OpSet2","OpSet3","SensorMeasure_1","SensorMeasure_2","SensorMeasure_3","SensorMeasure_4","SensorMeasure_5","SensorMeasure_6","SensorMeasure_7","SensorMeasure_8","SensorMeasure_9","SensorMeasure_10","SensorMeasure_11","SensorMeasure_12","SensorMeasure_13","SensorMeasure_14","SensorMeasure_15","SensorMeasure_16","SensorMeasure_17","SensorMeasure_18","SensorMeasure_19","SensorMeasure_20","SensorMeasure_21"]

In [29]:
given_no_of_cycles=[]
for i in range(1,len(df3['ID'].unique())+1):
    given_no_of_cycles.append(len(df3[df3['ID']==i]))
    print(len(df3[df3['ID']==i]))

given_no_of_cycles=np.array(given_no_of_cycles).reshape([cycle_ran_after.shape[0],1])

233
124
234
68
138
64
158
192
238
131
103
146
65
169
112
126
230
244
115
207
263
119
405
475
169
130
104
70
89
333
152
120
180
105
144
90
47
133
310
313
101
87
133
146
88
180
56
179
211
147
118
38
108
50
203
162
158
119
149
112
78
224
137
271
79
122
186
188
105
84
367
232
109
68
191
180
381
279
170
85
155
194
168
76
118
174
218
41
120
206
56
266
158
333
213
358
95
182
289
247

ValueError: cannot reshape array of size 100 into shape (259,1)

In [30]:
len(df3['ID'].unique())

100

In [31]:
cycle_ran_after=pd.read_csv('RUL_FD003.txt', sep=' ',header=None)
cycle_ran_after = cycle_ran_after.drop([1],axis='columns')
cycle_ran_after=np.array(cycle_ran_after)
cycle_ran_after

array([[ 44],
       [ 51],
       [ 27],
       [120],
       [101],
       [ 99],
       [ 71],
       [ 55],
       [ 55],
       [ 66],
       [ 77],
       [115],
       [115],
       [ 31],
       [108],
       [ 56],
       [136],
       [132],
       [ 85],
       [ 56],
       [ 18],
       [119],
       [ 78],
       [  9],
       [ 58],
       [ 11],
       [ 88],
       [144],
       [124],
       [ 89],
       [ 79],
       [ 55],
       [ 71],
       [ 65],
       [ 87],
       [137],
       [145],
       [ 22],
       [  8],
       [ 41],
       [131],
       [115],
       [128],
       [ 69],
       [111],
       [  7],
       [137],
       [ 55],
       [135],
       [ 11],
       [ 78],
       [120],
       [ 87],
       [ 87],
       [ 55],
       [ 93],
       [ 88],
       [ 40],
       [ 49],
       [128],
       [129],
       [ 58],
       [117],
       [ 28],
       [115],
       [ 87],
       [ 92],
       [103],
       [100],
       [ 63],
       [ 35],
       [ 45],
       [ 99],
       [117],
       [ 45],
       [ 27],
       [ 86],
       [ 20],
       [ 18],
       [133],
       [ 15],
       [  6],
       [145],
       [104],
       [ 56],
       [ 25],
       [ 68],
       [144],
       [ 41],
       [ 51],
       [ 81],
       [ 14],
       [ 67],
       [ 10],
       [127],
       [113],
       [123],
       [ 17],
       [  8],
       [ 28]], dtype=int64)

In [32]:
EOL = []
for i in df3['ID']:  # Use unique IDs to avoid redundant iterations
     EOL.append(given_no_of_cycles[i-1]+cycle_ran_after[i-1])
EOL=np.array(EOL).reshape([len(EOL),1])

In [34]:
EOL.shape
df3['EOL']=EOL
df3

,ID,Cycle,OpSet1,OpSet2,OpSet3,SensorMeasure_1,SensorMeasure_2,SensorMeasure_3,SensorMeasure_4,SensorMeasure_5,...,SensorMeasure_13,SensorMeasure_14,SensorMeasure_15,SensorMeasure_16,SensorMeasure_17,SensorMeasure_18,SensorMeasure_19,SensorMeasure_20,SensorMeasure_21,EOL
0,1,1,-0.0017,-0.0004,100.0,518.67,641.94,1581.93,1396.93,14.62,...,2387.94,8133.48,8.3760,0.03,391,2388,100.0,39.07,23.4468,277
1,1,2,0.0006,-0.0002,100.0,518.67,642.02,1584.86,1398.90,14.62,...,2388.01,8137.44,8.4062,0.03,391,2388,100.0,39.04,23.4807,277
2,1,3,0.0014,-0.0003,100.0,518.67,641.68,1581.78,1391.92,14.62,...,2387.94,8138.25,8.3553,0.03,391,2388,100.0,39.10,23.4244,277
3,1,4,0.0027,0.0001,100.0,518.67,642.20,1584.53,1395.34,14.62,...,2387.96,8137.07,8.3709,0.03,392,2388,100.0,38.97,23.4782,277
4,1,5,-0.0001,0.0001,100.0,518.67,642.46,1589.03,1395.86,14.62,...,2387.97,8134.20,8.4146,0.03,391,2388,100.0,39.09,23.3950,277
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16591,100,243,0.0011,-0.0003,100.0,518.67,643.04,1594.99,1411.28,14.62,...,2388.24,8162.24,8.2939,0.03,395,2388,100.0,39.40,23.4949,275
16592,100,244,-0.0024,0.0002,100.0,518.67,642.47,1591.27,1417.64,14.62,...,2388.26,8163.24,8.3247,0.03,394,2388,100.0,39.42,23.6011,275
16593,100,245,-0.0053,0.0002,100.0,518.67,642.70,1593.81,1412.70,14.62,...,2388.28,8162.12,8.3264,0.03,394,2388,100.0,39.43,23.5482,275
16594,100,246,-0.0006,0.0001,100.0,518.67,642.19,1595.63,1406.58,14.62,...,2388.33,8164.20,8.2908,0.03,395,2388,100.0,39.40,23.6687,275
16595,100,247,0.0023,0.0004,100.0,518.67,643.19,1592.54,1407.20,14.62,...,2388.29,8169.24,8.3191,0.03,392,2388,100.0,39.41,23.6536,275

In [35]:
df3['LR']=df3['Cycle']/df3['EOL']
#Drop ID and EOL

df3=df3.drop(columns=['ID','EOL'])
df3

,Cycle,OpSet1,OpSet2,OpSet3,SensorMeasure_1,SensorMeasure_2,SensorMeasure_3,SensorMeasure_4,SensorMeasure_5,SensorMeasure_6,...,SensorMeasure_13,SensorMeasure_14,SensorMeasure_15,SensorMeasure_16,SensorMeasure_17,SensorMeasure_18,SensorMeasure_19,SensorMeasure_20,SensorMeasure_21,LR
0,1,-0.0017,-0.0004,100.0,518.67,641.94,1581.93,1396.93,14.62,21.58,...,2387.94,8133.48,8.3760,0.03,391,2388,100.0,39.07,23.4468,0.003610
1,2,0.0006,-0.0002,100.0,518.67,642.02,1584.86,1398.90,14.62,21.58,...,2388.01,8137.44,8.4062,0.03,391,2388,100.0,39.04,23.4807,0.007220
2,3,0.0014,-0.0003,100.0,518.67,641.68,1581.78,1391.92,14.62,21.58,...,2387.94,8138.25,8.3553,0.03,391,2388,100.0,39.10,23.4244,0.010830
3,4,0.0027,0.0001,100.0,518.67,642.20,1584.53,1395.34,14.62,21.59,...,2387.96,8137.07,8.3709,0.03,392,2388,100.0,38.97,23.4782,0.014440
4,5,-0.0001,0.0001,100.0,518.67,642.46,1589.03,1395.86,14.62,21.58,...,2387.97,8134.20,8.4146,0.03,391,2388,100.0,39.09,23.3950,0.018051
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16591,243,0.0011,-0.0003,100.0,518.67,643.04,1594.99,1411.28,14.62,21.58,...,2388.24,8162.24,8.2939,0.03,395,2388,100.0,39.40,23.4949,0.883636
16592,244,-0.0024,0.0002,100.0,518.67,642.47,1591.27,1417.64,14.62,21.58,...,2388.26,8163.24,8.3247,0.03,394,2388,100.0,39.42,23.6011,0.887273
16593,245,-0.0053,0.0002,100.0,518.67,642.70,1593.81,1412.70,14.62,21.58,...,2388.28,8162.12,8.3264,0.03,394,2388,100.0,39.43,23.5482,0.890909
16594,246,-0.0006,0.0001,100.0,518.67,642.19,1595.63,1406.58,14.62,21.58,...,2388.33,8164.20,8.2908,0.03,395,2388,100.0,39.40,23.6687,0.894545
16595,247,0.0023,0.0004,100.0,518.67,643.19,1592.54,1407.20,14.62,21.58,...,2388.29,8169.24,8.3191,0.03,392,2388,100.0,39.41,23.6536,0.898182

In [36]:
df3.to_csv('text_classification_6.csv', index=None)

In [46]:
df4=pd.read_csv('test_FD004.txt', sep=' ',header=None)
df4

,0,1,2,3,4,5,6,7,8,9,...,18,19,20,21,22,23,24,25,26,27
0,1,1,20.0072,0.7000,100.0,491.19,606.67,1481.04,1227.81,9.35,...,8048.98,9.2229,0.02,362,2324,100.00,24.31,14.7007,NaN,NaN
1,1,2,24.9984,0.6200,60.0,462.54,536.22,1256.17,1031.48,7.05,...,7863.46,10.8632,0.02,306,1915,84.93,14.36,8.5748,NaN,NaN
2,1,3,42.0000,0.8420,100.0,445.00,549.23,1340.13,1105.88,3.91,...,8071.13,9.3960,0.02,328,2212,100.00,10.39,6.4365,NaN,NaN
3,1,4,42.0035,0.8402,100.0,445.00,549.19,1339.70,1107.26,3.91,...,8078.89,9.3594,0.02,328,2212,100.00,10.56,6.2367,NaN,NaN
4,1,5,35.0079,0.8400,100.0,449.44,555.10,1353.04,1117.80,5.48,...,8057.83,9.3030,0.02,333,2223,100.00,14.85,8.9326,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41209,248,277,41.9991,0.8401,100.0,445.00,550.30,1364.40,1129.17,3.91,...,8112.61,9.4427,0.02,331,2212,100.00,10.53,6.2620,NaN,NaN
41210,248,278,20.0026,0.7005,100.0,491.19,608.00,1494.75,1260.88,9.35,...,8086.83,9.2772,0.02,366,2324,100.00,24.33,14.6486,NaN,NaN
41211,248,279,34.9988,0.8413,100.0,449.44,555.92,1370.65,1130.97,5.48,...,8100.84,9.3982,0.02,336,2223,100.00,14.69,8.8389,NaN,NaN
41212,248,280,20.0027,0.7000,100.0,491.19,608.19,1489.11,1256.25,9.35,...,8085.24,9.2727,0.03,366,2324,100.00,24.44,14.6887,NaN,NaN
41213,248,281,35.0075,0.8402,100.0,449.44,556.40,1378.58,1140.70,5.48,...,8098.17,9.3964,0.02,335,2223,100.00,14.72,8.8502,NaN,NaN

In [47]:
df4 = df4.drop([26, 27], axis='columns', errors='ignore')

df4

,0,1,2,3,4,5,6,7,8,9,...,16,17,18,19,20,21,22,23,24,25
0,1,1,20.0072,0.7000,100.0,491.19,606.67,1481.04,1227.81,9.35,...,313.03,2387.78,8048.98,9.2229,0.02,362,2324,100.00,24.31,14.7007
1,1,2,24.9984,0.6200,60.0,462.54,536.22,1256.17,1031.48,7.05,...,163.61,2028.09,7863.46,10.8632,0.02,306,1915,84.93,14.36,8.5748
2,1,3,42.0000,0.8420,100.0,445.00,549.23,1340.13,1105.88,3.91,...,129.98,2387.95,8071.13,9.3960,0.02,328,2212,100.00,10.39,6.4365
3,1,4,42.0035,0.8402,100.0,445.00,549.19,1339.70,1107.26,3.91,...,129.48,2387.90,8078.89,9.3594,0.02,328,2212,100.00,10.56,6.2367
4,1,5,35.0079,0.8400,100.0,449.44,555.10,1353.04,1117.80,5.48,...,181.82,2387.87,8057.83,9.3030,0.02,333,2223,100.00,14.85,8.9326
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41209,248,277,41.9991,0.8401,100.0,445.00,550.30,1364.40,1129.17,3.91,...,130.87,2388.50,8112.61,9.4427,0.02,331,2212,100.00,10.53,6.2620
41210,248,278,20.0026,0.7005,100.0,491.19,608.00,1494.75,1260.88,9.35,...,314.51,2388.33,8086.83,9.2772,0.02,366,2324,100.00,24.33,14.6486
41211,248,279,34.9988,0.8413,100.0,449.44,555.92,1370.65,1130.97,5.48,...,182.76,2388.64,8100.84,9.3982,0.02,336,2223,100.00,14.69,8.8389
41212,248,280,20.0027,0.7000,100.0,491.19,608.19,1489.11,1256.25,9.35,...,314.17,2388.37,8085.24,9.2727,0.03,366,2324,100.00,24.44,14.6887
41213,248,281,35.0075,0.8402,100.0,449.44,556.40,1378.58,1140.70,5.48,...,181.88,2388.59,8098.17,9.3964,0.02,335,2223,100.00,14.72,8.8502

In [48]:
df4.columns=["ID","Cycle","OpSet1","OpSet2","OpSet3","SensorMeasure_1","SensorMeasure_2","SensorMeasure_3","SensorMeasure_4","SensorMeasure_5","SensorMeasure_6","SensorMeasure_7","SensorMeasure_8","SensorMeasure_9","SensorMeasure_10","SensorMeasure_11","SensorMeasure_12","SensorMeasure_13","SensorMeasure_14","SensorMeasure_15","SensorMeasure_16","SensorMeasure_17","SensorMeasure_18","SensorMeasure_19","SensorMeasure_20","SensorMeasure_21"]

In [49]:
given_no_of_cycles=[]
for i in range(1,len(df4['ID'].unique())+1):
    given_no_of_cycles.append(len(df4[df4['ID']==i]))
    print(len(df4[df4['ID']==i]))

given_no_of_cycles=np.array(given_no_of_cycles).reshape([cycle_ran_after.shape[0],1])

230
153
141
208
51
146
54
248
284
23
82
270
227
102
168
240
334
247
24
115
202
158
162
174
486
90
144
20
216
229
134
260
107
361
278
159
345
125
214
266
414
200
120
406
78
37
224
214
273
206
137
58
67
81
103
180
121
185
37
135
396
240
158
251
186
97
150
241
162
190
292
118
149
223
203
48
108
106
184
112
60
146
274
88
174
254
167
140
285
118
144
116
200
105
110
123
51
82
237
196
166
443
145
65
351
148
121
145
66
348
342
88
132
218
82
161
97
178
228
170
194
117
236
230
21
220
98
139
315
107
193
115
74
266
435
56
291
239
88
160
19
69
327
34
102
84
116
126
320
202
285
195
130
122
161
28
138
171
160
122
257
99
122
29
178
63
99
74
34
48
355
132
151
135
116
185
146
279
262
367
199
98
125
154
203
47
121
157
107
200
71
203
263
214
186
70
196
115
177
115
139
222
87
19
95
291
179
180
171
135
206
261
288
102
72
264
141
63
110
65
176
178
305
152
39
59
62
126
20
157
230
370
111
179
362
176
221
177
28
204
42
112
199
184
63
29
94
281

In [50]:
len(df4['ID'].unique())

248

In [51]:
cycle_ran_after=pd.read_csv('RUL_FD004.txt', sep=' ',header=None)
cycle_ran_after = cycle_ran_after.drop([1],axis='columns')
cycle_ran_after=np.array(cycle_ran_after)
cycle_ran_after

array([[ 22],
       [ 39],
       [107],
       [ 75],
       [149],
       [ 78],
       [ 94],
       [ 14],
       [ 99],
       [162],
       [143],
       [  7],
       [ 71],
       [105],
       [ 12],
       [160],
       [162],
       [104],
       [194],
       [ 82],
       [ 91],
       [ 11],
       [ 26],
       [142],
       [ 39],
       [ 92],
       [ 76],
       [124],
       [ 64],
       [118],
       [  6],
       [ 22],
       [147],
       [126],
       [ 36],
       [ 73],
       [ 89],
       [ 11],
       [151],
       [ 10],
       [ 97],
       [ 30],
       [ 42],
       [ 60],
       [ 85],
       [134],
       [ 34],
       [ 45],
       [ 24],
       [ 86],
       [119],
       [151],
       [142],
       [176],
       [157],
       [ 67],
       [ 97],
       [  8],
       [154],
       [139],
       [ 51],
       [ 33],
       [184],
       [ 46],
       [ 12],
       [133],
       [ 46],
       [ 46],
       [ 12],
       [ 33],
       [ 15],
       [176],
       [ 23],
       [ 89],
       [124],
       [163],
       [ 25],
       [ 74],
       [ 78],
       [114],
       [ 96],
       [ 10],
       [172],
       [166],
       [115],
       [ 70],
       [ 94],
       [ 56],
       [ 86],
       [ 96],
       [ 50],
       [ 73],
       [154],
       [129],
       [171],
       [ 71],
       [105],
       [113],
       [ 37],
       [  7],
       [ 13],
       [ 22],
       [  9],
       [120],
       [100],
       [107],
       [ 41],
       [153],
       [126],
       [ 59],
       [ 18],
       [ 66],
       [ 13],
       [ 14],
       [139],
       [ 13],
       [ 75],
       [  8],
       [109],
       [137],
       [ 41],
       [192],
       [ 23],
       [ 86],
       [184],
       [ 15],
       [195],
       [126],
       [120],
       [165],
       [101],
       [116],
       [126],
       [ 36],
       [  7],
       [122],
       [159],
       [ 88],
       [173],
       [146],
       [130],
       [108],
       [ 53],
       [162],
       [ 59],
       [100],
       [ 56],
       [145],
       [ 76],
       [ 57],
       [ 31],
       [ 88],
       [173],
       [ 34],
       [  7],
       [133],
       [172],
       [  6],
       [ 22],
       [ 83],
       [ 82],
       [ 84],
       [ 95],
       [174],
       [111],
       [ 72],
       [109],
       [ 87],
       [179],
       [158],
       [126],
       [ 12],
       [  8],
       [ 10],
       [123],
       [103],
       [ 12],
       [106],
       [ 12],
       [ 32],
       [ 37],
       [116],
       [ 15],
       [ 10],
       [ 46],
       [142],
       [ 24],
       [135],
       [ 56],
       [ 43],
       [178],
       [ 71],
       [104],
       [ 15],
       [166],
       [ 89],
       [ 36],
       [ 11],
       [ 92],
       [ 96],
       [ 59],
       [ 13],
       [167],
       [151],
       [154],
       [109],
       [116],
       [ 91],
       [ 11],
       [ 88],
       [108],
       [ 76],
       [ 14],
       [ 89],
       [145],
       [ 17],
       [ 66],
       [154],
       [ 41],
       [182],
       [ 73],
       [ 39],
       [ 58],
       [ 14],
       [145],
       [ 88],
       [162],
       [189],
       [120],
       [ 98],
       [ 33],
       [184],
       [110],
       [ 68],
       [ 24],
       [ 75],
       [ 18],
       [ 16],
       [166],
       [ 98],
       [176],
       [ 81],
       [118],
       [ 35],
       [131],
       [194],
       [112],
       [ 26]], dtype=int64)

In [52]:
EOL = []
for i in df4['ID']:  # Use unique IDs to avoid redundant iterations
     EOL.append(given_no_of_cycles[i-1]+cycle_ran_after[i-1])
EOL=np.array(EOL).reshape([len(EOL),1])

In [53]:
EOL.shape
df4['EOL']=EOL
df4

,ID,Cycle,OpSet1,OpSet2,OpSet3,SensorMeasure_1,SensorMeasure_2,SensorMeasure_3,SensorMeasure_4,SensorMeasure_5,...,SensorMeasure_13,SensorMeasure_14,SensorMeasure_15,SensorMeasure_16,SensorMeasure_17,SensorMeasure_18,SensorMeasure_19,SensorMeasure_20,SensorMeasure_21,EOL
0,1,1,20.0072,0.7000,100.0,491.19,606.67,1481.04,1227.81,9.35,...,2387.78,8048.98,9.2229,0.02,362,2324,100.00,24.31,14.7007,252
1,1,2,24.9984,0.6200,60.0,462.54,536.22,1256.17,1031.48,7.05,...,2028.09,7863.46,10.8632,0.02,306,1915,84.93,14.36,8.5748,252
2,1,3,42.0000,0.8420,100.0,445.00,549.23,1340.13,1105.88,3.91,...,2387.95,8071.13,9.3960,0.02,328,2212,100.00,10.39,6.4365,252
3,1,4,42.0035,0.8402,100.0,445.00,549.19,1339.70,1107.26,3.91,...,2387.90,8078.89,9.3594,0.02,328,2212,100.00,10.56,6.2367,252
4,1,5,35.0079,0.8400,100.0,449.44,555.10,1353.04,1117.80,5.48,...,2387.87,8057.83,9.3030,0.02,333,2223,100.00,14.85,8.9326,252
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41209,248,277,41.9991,0.8401,100.0,445.00,550.30,1364.40,1129.17,3.91,...,2388.50,8112.61,9.4427,0.02,331,2212,100.00,10.53,6.2620,307
41210,248,278,20.0026,0.7005,100.0,491.19,608.00,1494.75,1260.88,9.35,...,2388.33,8086.83,9.2772,0.02,366,2324,100.00,24.33,14.6486,307
41211,248,279,34.9988,0.8413,100.0,449.44,555.92,1370.65,1130.97,5.48,...,2388.64,8100.84,9.3982,0.02,336,2223,100.00,14.69,8.8389,307
41212,248,280,20.0027,0.7000,100.0,491.19,608.19,1489.11,1256.25,9.35,...,2388.37,8085.24,9.2727,0.03,366,2324,100.00,24.44,14.6887,307
41213,248,281,35.0075,0.8402,100.0,449.44,556.40,1378.58,1140.70,5.48,...,2388.59,8098.17,9.3964,0.02,335,2223,100.00,14.72,8.8502,307

In [54]:
df4['LR']=df4['Cycle']/df4['EOL']
#Drop ID and EOL

df4=df4.drop(columns=['ID','EOL'])
df4

,Cycle,OpSet1,OpSet2,OpSet3,SensorMeasure_1,SensorMeasure_2,SensorMeasure_3,SensorMeasure_4,SensorMeasure_5,SensorMeasure_6,...,SensorMeasure_13,SensorMeasure_14,SensorMeasure_15,SensorMeasure_16,SensorMeasure_17,SensorMeasure_18,SensorMeasure_19,SensorMeasure_20,SensorMeasure_21,LR
0,1,20.0072,0.7000,100.0,491.19,606.67,1481.04,1227.81,9.35,13.60,...,2387.78,8048.98,9.2229,0.02,362,2324,100.00,24.31,14.7007,0.003968
1,2,24.9984,0.6200,60.0,462.54,536.22,1256.17,1031.48,7.05,9.00,...,2028.09,7863.46,10.8632,0.02,306,1915,84.93,14.36,8.5748,0.007937
2,3,42.0000,0.8420,100.0,445.00,549.23,1340.13,1105.88,3.91,5.69,...,2387.95,8071.13,9.3960,0.02,328,2212,100.00,10.39,6.4365,0.011905
3,4,42.0035,0.8402,100.0,445.00,549.19,1339.70,1107.26,3.91,5.69,...,2387.90,8078.89,9.3594,0.02,328,2212,100.00,10.56,6.2367,0.015873
4,5,35.0079,0.8400,100.0,449.44,555.10,1353.04,1117.80,5.48,7.97,...,2387.87,8057.83,9.3030,0.02,333,2223,100.00,14.85,8.9326,0.019841
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41209,277,41.9991,0.8401,100.0,445.00,550.30,1364.40,1129.17,3.91,5.72,...,2388.50,8112.61,9.4427,0.02,331,2212,100.00,10.53,6.2620,0.902280
41210,278,20.0026,0.7005,100.0,491.19,608.00,1494.75,1260.88,9.35,13.66,...,2388.33,8086.83,9.2772,0.02,366,2324,100.00,24.33,14.6486,0.905537
41211,279,34.9988,0.8413,100.0,449.44,555.92,1370.65,1130.97,5.48,8.00,...,2388.64,8100.84,9.3982,0.02,336,2223,100.00,14.69,8.8389,0.908795
41212,280,20.0027,0.7000,100.0,491.19,608.19,1489.11,1256.25,9.35,13.66,...,2388.37,8085.24,9.2727,0.03,366,2324,100.00,24.44,14.6887,0.912052
41213,281,35.0075,0.8402,100.0,449.44,556.40,1378.58,1140.70,5.48,8.00,...,2388.59,8098.17,9.3964,0.02,335,2223,100.00,14.72,8.8502,0.915309

In [55]:
df4.to_csv('text_classification_7.csv', index=None)

Testing on given Test-Dataset

In [56]:
df1=pd.read_csv('text_classification_4.csv')
df2=pd.read_csv('text_classification_5.csv')
df3=pd.read_csv('text_classification_6.csv')
df4=pd.read_csv('text_classification_7.csv')

In [59]:
df=pd.concat([df1,df2,df3,df4])

In [60]:
X_test=df.iloc[:,0:-1]
y_test=df.iloc[:,-1]

In [62]:
from sklearn.metrics import confusion_matrix, accuracy_score

y_pred_RF=RF_randSer.predict(X_test)
cm=pd.DataFrame(confusion_matrix(y_test,y_pred_RF,normalize='true')*100)
colormap=sns.color_palette('Reds')
sns.heatmap(cm,annot=True,cmap=colormap)
accuracy_score(y_test,y_pred_RF)

NameError: name 'RF_randSer' is not defined

    112
0     98
1     69
2     82
3     91
4     93
..   ...
94   137
95    82
96    59
97   117
98    20

[99 rows x 1 columns]